security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
 
    providers:
        in_memory:
            memory:
                users:
                    Mcho:  { password: 123456!, roles: [ 'ROLE_ADMIN' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:          
 
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                always_use_default_target_path: true
                default_target_path:            /admin/dashboard
                use_referer:                    true
                login_path: tgw_admin_index
                check_path: login_check
            logout:
                path:   logout
                target: tgw_admin_index
                
 
 
    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }