blog_articles:
    path:    /articles/{page}
    defaults: { _controller: tgwBlogBundle:Article:articles, page: 1 }
    requirements:
        page: \d+

blog_article_show:
    path:   /article/{id}/{slug}
    defaults: { _controller: tgwBlogBundle:Article:show }

blog_home:
    path:     /
    defaults: { _controller: tgwBlogBundle:Accueil:index }

blog_test:
    path:     /test
    defaults: { _controller: tgwBlogBundle:Article:ajouterArticle }

blog_article_remove:
    path:     /admin/article/supprimer/{id}
    defaults: { _controller:tgwBlogBundle:Article:supprimer}

blog_contact:
    path:   /contact/{name}
    defaults: { _controller:tgwBlogBundle:Contact:index}

blog_contact_send:
    path: /contact/send/{name}
    defaults: { _controller:tgwBlogBundle:Contact:send}

blog_rechercher:
    path: /rechercher
    defaults: { _controller:tgwBlogBundle:Recherche:rechercher}
