blog_articles:
    path:    /articles/{page}
    defaults: { _controller: tgwBlogBundle:Article:articles, page: 1 }
    requirements:
        page: \d+

blog_article_show:
    path:   /article/{id}
    defaults: { _controller: tgwBlogBundle:Article:show }

blog_home:
    path:     /
    defaults: { _controller: tgwBlogBundle:Accueil:index }

blog_test:
    path:     /test
    defaults: { _controller: tgwBlogBundle:Article:ajouterArticle }

blog_article_remove:
    path:     /admin/article/supprimer/{id}
    defaults: { _controller:tgwBlogBundle:Article:supprimer}
