tgw_admin_index:
    path:   /admin
    defaults: { _controller: tgwAdminBundle:Admin:index }

create:
    path:   /user/create
    defaults: { _controller: tgwAdminBundle:User:create }

dashboard:
    path:   /admin/dashboard
    defaults: { _controller: tgwAdminBundle:Admin:dashboard}

articles:
    path:   /admin/dashboard/articles
    defaults: { _controller: tgwAdminBundle:Admin:articles}

editer_article:
    path:   /admin/dashboard/articles/editer/{id}
    defaults: { _controller: tgwBlogBundle:Article:editer}

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout