tgw_admin_index:
    path:   /admin
    defaults: { _controller: tgwAdminBundle:Admin:index }
tgw_admin_rediger:
    path: /admin/dashboard/article/rediger
    defaults: { _controller: tgwAdminBundle:Admin:rediger }
create:
    path:   /user/create
    defaults: { _controller: tgwAdminBundle:User:create }

dashboard:
    path:   /admin/dashboard
    defaults: { _controller: tgwAdminBundle:Admin:dashboard}

articles:
    path:   /admin/dashboard/articles
    defaults: { _controller: tgwAdminBundle:Admin:articles}

categories:
    path:   /admin/dashboard/categories
    defaults: { _controller: tgwAdminBundle:Categorie:categories}

tgw_admin_creer_article:
    path:   /admin/dashboard/article/creer
    defaults: { _controller: tgwAdminBundle:Admin:creer}

tgw_admin_supprimer_article:
    path:   /admin/dashboard/article/supprimer/{id}
    defaults: { _controller: tgwAdminBundle:Admin:supprimer }

tgw_admin_editer_article:
    path:   /admin/dashboard/article/editer/{id}
    defaults: { _controller: tgwAdminBundle:Admin:editer}

tgw_admin_update_article:
    path:   /admin/dashboard/article/edition
    defaults: { _controller: tgwAdminBundle:Admin:update}

tgw_admin_publier_article:
    path:   /admin/dashboard/article/publie
    defaults: { _controller: tgwAdminBundle:Admin:publie}

tgw_admin_depublier_article:
    path:   /admin/dashboard/article/depublie
    defaults: { _controller: tgwAdminBundle:Admin:depublie}

tgw_admin_rediger_categorie:
    path:   /admin/dashboard/categorie/rediger
    defaults: { _controller: tgwAdminBundle:Categorie:rediger}

tgw_admin_creer_categorie:
    path:   /admin/dashboard/categorie/creer
    defaults: { _controller: tgwAdminBundle:Categorie:creer}

tgw_admin_index_auteurs:
    path:   /admin/dashboard/auteurs
    defaults: { _controller: tgwAdminBundle:Auteur:index}

tgw_admin_rediger_auteur:
    path:   /admin/dashboard/auteur/rediger
    defaults: { _controller: tgwAdminBundle:Auteur:rediger}

tgw_admin_creer_auteur:
    path:   /admin/dashboard/auteur/creer
    defaults: { _controller: tgwAdminBundle:Auteur:creer}

tgw_admin_editer_auteur:
    path:   /admin/dashboard/auteur/editer/{id}
    defaults: { _controller: tgwAdminBundle:Auteur:editer}

tgw_admin_update_auteur:
    path:   /admin/dashboard/auteur/update
    defaults: { _controller: tgwAdminBundle:Auteur:update}

tgw_admin_suppimer_auteur:
    path:   /admin/dashboard/auteur/supprimer/{id}

tgw_admin_filemanager:
    path:   /admin/dashboard/manager
    defaults: { _controller: tgwAdminBundle:FileManager:index}



login_check:
    pattern:   /login_check

logout:
    pattern:   /logout



