tgw_admin_index:
    path:   /admin
    defaults: { _controller: tgwAdminBundle:Admin:index }
tgw_admin_rediger:
    path: /admin/dashboard/article/rediger
    defaults: { _controller: tgwAdminBundle:Admin:rediger }
create:
    path:   /user/create
    defaults: { _controller: tgwAdminBundle:User:create }

dashboard:
    path:   /admin/dashboard
    defaults: { _controller: tgwAdminBundle:Admin:dashboard}

articles:
    path:   /admin/dashboard/articles
    defaults: { _controller: tgwAdminBundle:Admin:articles}

tgw_admin_creer_article:
    path:   /admin/dashboard/article/creer
    defaults: { _controller: tgwAdminBundle:Admin:creer}

tgw_admin_supprimer_article:
    path:   /admin/dashboard/article/supprimer/{id}
    defaults: { _controller: tgwAdminBundle:Admin:supprimer }

tgw_admin_editer_article:
    path:   /admin/dashboard/article/editer/{id}
    defaults: { _controller: tgwAdminBundle:Admin:editer}

tgw_admin_update_article:
    path:   /admin/dashboard/article/edition
    defaults: { _controller: tgwAdminBundle:Admin:update}

tgw_admin_publier_article:
    path:   /admin/dashboard/article/publie
    defaults: { _controller: tgwAdminBundle:Admin:publie}

tgw_admin_depublier_article:
    path:   /admin/dashboard/article/depublie
    defaults: { _controller: tgwAdminBundle:Admin:depublie}

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout