parameters:
#    tgw_admin.example.class: tgw\AdminBundle\Example

services:
#    tgw_admin.example:
#        class: %tgw_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
